apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory }}
              cpu: {{ .Values.frontend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory }}
              cpu: {{ .Values.frontend.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: {{ .Values.frontend.probes.liveness.port }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: {{ .Values.frontend.probes.readiness.port }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  # NodePort нужен для ALB с target-type: ip можно оставить ClusterIP
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
